sudo: required
dist: trusty
before_install:
  - curl "https://gist.githubusercontent.com/ljvmiranda921/6055d03dc264bfca0ea8c421ec6a2b41/raw/b965460d8f792c5a825a3a088d56a4dce37b852f/tlsetup.sh" -o tlsetup.sh
  - chmod +x tlsetup.sh 

install:
  - ./tlsetup.sh

script:
  - make latex COMPILER=xelatex

deploy:
  provider: script
  skip_cleanup: true
  before_script: 
  - curl "https://raw.githubusercontent.com/Sloy/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  script:
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-latest.pdf
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-${TRAVIS_JOB_NUMBER}.pdf
