dist: trusty
sudo: required

language: c

branches:
  only:
  - master

env:
  - DOCOPTIONS=heros
  - DOCOPTIONS=print
  - DOCOPTIONS=nocolors
  - DOCOPTIONS=a4paper
  - DOCOPTIONS=alegreya
  - DOCOPTIONS=merriweather
  - DOCOPTIONS=nunito
  - DOCOPTIONS=roboto

before_install: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$DOCOPTIONS" = "heros" ]; then
    git checkout --orphan $TRAVIS_BRANCH-pdf
    git rm -rf .
    touch README
    git add README
    git -c user.name='travis' -c user.email='travis' commit -m "Initial commit"
    git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    git checkout $TRAVIS_BRANCH
  fi
  
install:
  - sudo apt-get -qq update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install texlive-full fonts-font-awesome biber
  
before_script: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$DOCOPTIONS" != "heros" ]; then
    git checkout -b $TRAVIS_BRANCH-pdf 
    git branch -u https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH-pdf
    git pull -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    git checkout $TRAVIS_BRANCH
  fi

script: make custom

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git stash -q
    git checkout $TRAVIS_BRANCH-pdf
    git pull -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    git checkout -f master cv-$DOCOPTIONS.pdf
    git add -f cv-$DOCOPTIONS.pdf
    git -c user.name='travis' -c user.email='travis' commit -m "current pdf with $DOCOPTIONS option"
    git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
  fi

jobs:
  include:
    - stage: Deploy
      env:
        - DOCOPTIONS=a4paper
      install:
        - sudo apt-get -qq update
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install imagemagick
      script: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git fetch -q -f
          git checkout -f $TRAVIS_BRANCH-pdf
          git pull https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
          mkdir -p png
          mogrify -density 288 -resize 25% -format png *.pdf[0]
          mv *.png png/
          git add -f png/*.png
          git -c user.name='travis' -c user.email='travis' commit -m "pngs for readme"
          git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf    
        fi
