dist: trusty
sudo: required

language: c

addons:
  apt:
    update: true
    packages:
      - texlive-full
      - fonts-font-awesome
      - biber


env:
  - DOCOPTIONS=print
  - DOCOPTIONS=nocolors
  - DOCOPTIONS=a4paper
  - DOCOPTIONS=heros
  - DOCOPTIONS=alegreya
  - DOCOPTIONS=merriweather
  - DOCOPTIONS=nunito
  - DOCOPTIONS=roboto


script: 
  - make custom DOCOPTIONS=$(DOCOPTIONS)

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd $TRAVIS_BUILD_DIR
    git checkout --orphan $TRAVIS_BRANCH-pdf
    git rm -rf .
    git add -f *.pdf
    git -c user.name='travis' -c user.email='travis' commit -m "current pdf with $DOCOPTIONS option"
    git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
  fi