dist: trusty
os: linux

sudo: required
language: generic
services: docker

branches:
  only:
  - master

jobs:
  include:
    - stage: Compile
      
      install:
        - docker pull christianhallerx/tect-docker

      script:
         - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind christianhallerx/tect-docker /bin/sh -c "tectonic cv.tex; tectonic coverletter.tex"