sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive texlive-latex-extra texlive-generic-extra texlive-fonts-recommended texlive-fonts-extra dvipng texlive-latex-recommended texlive-xetex latex-xcolor fonts-lmodern
  - sudo fmtutil-sys --all

script:
  - make pdf clean

deploy:
  provider: script
  skip_cleanup: true
  before_script: 
  - curl "https://raw.githubusercontent.com/Sloy/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  script:
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-latest.pdf
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-${TRAVIS_JOB_NUMBER}.pdf
