dist: trusty
sudo: required

language: c

branches:
  only:
  - master

before_install: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
    git checkout --orphan $TRAVIS_BRANCH-pdf
    git rm -rf .
    touch Readme.md
    git add Readme.md
    git -c user.name='travis' -c user.email='travis' commit -m "Initial commit"
    git push -q -f upstream $TRAVIS_BRANCH-pdf
    git checkout $TRAVIS_BRANCH
  fi
  
install:
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2016
  - sudo apt-get -qq update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install texlive-full fonts-font-awesome biber
  
before_script: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
    git fetch upstream
    git checkout $TRAVIS_BRANCH-pdf
    git pull -f -q upstream $TRAVIS_BRANCH-pdf
    git checkout $TRAVIS_BRANCH
  fi

script: 
  - DOCOPTIONS=heros
  - make custom
  - DOCOPTIONS=print
  - make custom
  - DOCOPTIONS=nocolors	
  - make custom
  - DOCOPTIONS=a4paper
  - make custom
  - DOCOPTIONS=alegreya	
  - make custom
  - DOCOPTIONS=merriweather	
  - make custom
  - DOCOPTIONS=nunito	
  - make custom
  - DOCOPTIONS=roboto
  - make custom

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git stash -q
    git fetch upstream
    git checkout $TRAVIS_BRANCH-pdf
    git pull -q -f upstream $TRAVIS_BRANCH-pdf
    git checkout -f master cv-$DOCOPTIONS.pdf
    git add -f cv-$DOCOPTIONS.pdf
    git -c user.name='travis' -c user.email='travis' commit -m "current pdf with $DOCOPTIONS option"
    git push -q upstream $TRAVIS_BRANCH-pdf
  fi

jobs:
  include:
    - stage: Deploy
      install:
        - sudo apt-get -qq update
        - sudo -E apt-get -yq --reinstall --no-install-suggests --no-install-recommends --force-yes install ghostscript imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev
      script: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
          git fetch -q upstream
          git checkout $TRAVIS_BRANCH-pdf
          git pull -f upstream $TRAVIS_BRANCH-pdf
          mkdir -p png
          mogrify -density 288 -resize 25% -format png *.pdf
          mv *.png png/
          git add -f png/*.png
          git -c user.name='travis' -c user.email='travis' commit -m "pngs for readme"
          git push -q upstream $TRAVIS_BRANCH-pdf    
        fi
