sudo: required
dist: trusty
services:
  - docker

script:
  - ddocker run -v $PWD:/doc/  -t -i thomasweise/texlive make pdf clean

deploy:
  provider: script
  skip_cleanup: true
  before_script: 
  - curl "https://raw.githubusercontent.com/Sloy/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  script:
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-latest.pdf
  - ./dropbox_uploader.sh upload _build/cv.pdf ${TRAVIS_BRANCH}/cv-${TRAVIS_JOB_NUMBER}.pdf
