dist: trusty
os: linux

language: generic
services: docker

branches:
  only:
  - master

jobs:
  include:
    - stage: Compile
      
      install:
        - docker pull christianhallerx/tect-docker

      script:
         docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind christianhallerx/tect-docker /bin/bash \
         echo "----- CV -----"; \
         tectonic --keep-intermediates --reruns 0 cv.tex && \
         biber cv && \
         tectonic cv.tex || exit 1; \
         echo "----- CoverLetter -----"; \
         tectonic coverletter.tex && exit 1'\